### ISSUE TITLE
Release tarball / bz2 / whatever?

### ISSUE THREAD

**Issue by brennen** [tam7t/droplan#10]
Very minor thing, but many systems don't come with `unzip` preinstalled.  Detailed instructions could skip one step if there was a release `.tar.gz` / `.gz` / `.bz2`.  (I s'pose there's not much point in tarring it up since it's literally a single file...)

**Comment by tam7t** [comment]
`.tar.gz` seems like a reasonable addition!

**Comment by tam7t** [comment]
Updated v1 release and the `Makefile` for future releases
