### ISSUE TITLE
support tags

### ISSUE THREAD

**Issue by tam7t** [tam7t/droplan#17]
digitalocean now supports [tagged droplets](https://www.digitalocean.com/community/tutorials/how-to-use-droplet-tagging-with-the-digitalocean-api). It would be nice for `droplan` to support using these tags to control access.

One thought would be for `droplan` to accept (one or more?) `tag`s for droplets that have access to the box.

**Comment by josegonzalez** [comment]
Should this be closed?

**Comment by tam7t** [comment]
@josegonzalez Almost! I just want to update the readme and cut a binary release before I close it

**Comment by tam7t** [comment]
Finally got around to testing this and cut the [v.1.1.0 release](https://github.com/tam7t/droplan/releases/tag/v1.1.0)
