### ISSUE TITLE
Allow opening some ports to access

### ISSUE THREAD

**Issue by josegonzalez** [tam7t/droplan#21]
In conjunction with #20, it would be cool if we could still allow access to certain ports even when we block traffic overall. For instance, users that want to setup a jumpbox could whitelist port 22 and otherwise have the same config as every other server.

**Comment by tam7t** [comment]
Could this be done by adding an explicit allow rule earlier in the chain than the `droplan` managed rules?

**Comment by josegonzalez** [comment]
That works, didn't think about that.

**Comment by tam7t** [comment]
Thanks for opening the issue, please re-open if there is a reason that doesn't work out!
