### ISSUE TITLE
Whitelist IP addresses

### ISSUE THREAD

**Issue by josegonzalez** [tam7t/droplan#22]
In conjunction with #20, it would be cool if we could also allow access to users coming from a certain IP address. You could even do something like:

```
ALLOWED_ACCESS=EXTERNAL_IP:HOST_PORT,EXTERNAL_IP:HOST_PORT
```

**Comment by tam7t** [comment]
I'd like to keep `droplan` limited in responsibility to just managing an iptables chain of addresses fetched from the digitalocean api. I think something like this might be better suited to a configuration management system or a separate `iptables` script. If there is something that `droplan` does that interferes with that usage then I'd definitely want to address that.

**Comment by josegonzalez** [comment]
Ditto!
